"""added games table and relationships

Revision ID: 12e10b70155c
Revises: 09fe8fc9931c
Create Date: 2023-09-02 13:15:22.001049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e10b70155c'
down_revision = '09fe8fc9931c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rgb', sa.String(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.Column('guesses', sa.Integer(), nullable=True),
    sa.Column('percent_score', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('games_played')
        batch_op.drop_column('games_won')
        batch_op.drop_column('games_lost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_lost', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('games_won', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('games_played', sa.INTEGER(), nullable=True))

    op.drop_table('games')
    # ### end Alembic commands ###
